---
id: 982fa87351
images:
- description: 'image #1'
  id: image_1
  path: images/mlops-zoomcamp/image_f4090a89.png
question: 'Runtime Error: Failed to Reach API on Prefect'
sort_order: 22
---

**Problem:** When running `evidently_metrics_calculation.py`, the following error is shown:

```
RuntimeError: Cannot create flow run. Failed to reach API at https://api.prefect.cloud/api/accounts/ee976605-4ca7-4a27-b5e3-0a37da3c7678/workspaces/78b23cf5-38bb-4d8b-9888-5bf8070d6d62/
```

**Solution:**

- Register or sign up at [https://app.prefect.cloud/account/](https://app.prefect.cloud/account/)

<{IMAGE:image_1}>
