---
id: 424d68d110
question: Error when running ImageDataGenerator.flow_from_dataframe
sort_order: 11
---

Error: ImageDataGenerator name 'scipy' is not defined.

To resolve this issue:

1. Ensure that `scipy` is installed in your environment:
   
   ```bash
   pip install scipy
   ```

2. Restart the Jupyter kernel and try running the code again.